# -*- coding: utf-8 -*-
"""AQI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SiVvy85DgNh1FxHmZSYIM1s_UllnGnDV
"""

import numpy as np
import seaborn as sns
import pandas as pd
df=pd.read_csv('AQIFinalDataset.csv')
df.head(10)

df.info()

df.isnull().sum()

import plotly.express as px
fig=px.scatter(df, x='Location', y='AQI')
fig.show()

import plotly.express as px
fig=px.scatter(df, x='Time', y='AQI')
fig.show()

import plotly.express as px
fig=px.scatter(df, x='PM2.5', y='AQI')
fig.show()

import plotly.express as px
fig=px.scatter(df, x='PM10', y='AQI')
fig.show()

import plotly.express as px
fig=px.scatter(df, x='CO', y='AQI')
fig.show()

import plotly.express as px
fig=px.scatter(df, x='NO2', y='AQI')
fig.show()

import plotly.express as px
fig=px.scatter(df, x='SO2', y='AQI')
fig.show()

import plotly.express as px
fig=px.scatter(df, x='O3', y='AQI')
fig.show()

df.columns

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

# Select features and target
X = df[["CO", "SO2", "NO2", "O3", "PM2.5", "PM10"]]  # Feature variables
Y = df["AQI"]  # Target variable

# Split dataset into training and testing sets
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size=0.2, random_state=20)

"""Linear Regression Model:"""

lin_reg = LinearRegression()
lin_reg.fit(Xtrain, Ytrain)
y_pred_lin = lin_reg.predict(Xtest)
mse_lin = mean_squared_error(Ytest, y_pred_lin)
rmse_lin = np.sqrt(mse_lin)
r2_lin = r2_score(Ytest, y_pred_lin)
mae_lin = mean_absolute_error(Ytest, y_pred_lin)
print("Linear Regression:")
print(f"Mean Squared Error (MSE): {mse_lin:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_lin:.2f}")
print(f"R2 Score: {r2_lin:.2f}")
print(f"Mean Absolute Error (MAE): {mae_lin:.2f}\n")

"""Decision Tree Model:"""

dt_reg = DecisionTreeRegressor(max_depth=5, random_state=15)
dt_reg.fit(Xtrain, Ytrain)
y_pred_dt = dt_reg.predict(Xtest)
mse_dt = mean_squared_error(Ytest, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)
r2_dt = r2_score(Ytest, y_pred_dt)
mae_dt = mean_absolute_error(Ytest, y_pred_dt)
print("Decision Tree:")
print(f"Mean Squared Error (MSE): {mse_dt:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_dt:.2f}")
print(f"R2 Score: {r2_dt:.2f}")
print(f"Mean Absolute Error (MAE): {mae_dt:.2f}\n")

"""Support Vector Regression Model:"""

svr_reg = SVR(kernel='rbf')
svr_reg.fit(Xtrain, Ytrain)
y_pred_svr = svr_reg.predict(Xtest)
mse_svr = mean_squared_error(Ytest, y_pred_svr)
rmse_svr = np.sqrt(mse_svr)
r2_svr = r2_score(Ytest, y_pred_svr)
mae_svr = mean_absolute_error(Ytest, y_pred_svr)
print("Support Vector Regression:")
print(f"Mean Squared Error (MSE): {mse_svr:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_svr:.2f}")
print(f"R2 Score: {r2_svr:.2f}")
print(f"Mean Absolute Error (MAE): {mae_svr:.2f}\n")

"""Random Forest Regression Model:"""

rf_reg = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=15)
rf_reg.fit(Xtrain, Ytrain)
y_pred_rf = rf_reg.predict(Xtest)
mse_rf = mean_squared_error(Ytest, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(Ytest, y_pred_rf)
mae_rf = mean_absolute_error(Ytest, y_pred_rf)
print("Random Forest Regression:")
print(f"Mean Squared Error (MSE): {mse_rf:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_rf:.2f}")
print(f"R2 Score: {r2_rf:.2f}")
print(f"Mean Absolute Error (MAE): {mae_rf:.2f}\n")

"""Naive Bayes Classifier"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Select features and target
# Features: CO, SO2, NO2, O3, PM2.5, PM10
# Target: AQI Category (categorical)
X = df[['CO', 'SO2', 'NO2', 'O3', 'PM2.5', 'PM10']]
y = df['AQI Category']

# Handle missing values (if any)
X = X.fillna(X.mean())
y = y.fillna(y.mode()[0])  # Use mode for categorical target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features (GaussianNB assumes features are normally distributed)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize and train the Gaussian Naive Bayes classifier
nb_clf = GaussianNB(var_smoothing=1e-9)
nb_clf.fit(X_train_scaled, y_train)

# Make predictions
y_pred = nb_clf.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Gaussian Naive Bayes Classifier for AQI Category Prediction:")
print(f"Accuracy: {accuracy:.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Optional: Predict probabilities for a sample test instance
sample_instance = X_test_scaled[0].reshape(1, -1)
probabilities = nb_clf.predict_proba(sample_instance)
class_names = nb_clf.classes_
print("\nSample Prediction Probabilities:")
for class_name, prob in zip(class_names, probabilities[0]):
    print(f"{class_name}: {prob:.4f}")

"""Multilayer Perceptron Regressor"""

import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

mlp_reg = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=2000, random_state=15)
mlp_reg.fit(Xtrain, Ytrain)
y_pred_mlp = mlp_reg.predict(Xtest)
mse_mlp = mean_squared_error(Ytest, y_pred_mlp)
rmse_mlp = np.sqrt(mse_mlp)
r2_mlp = r2_score(Ytest, y_pred_mlp)
mae_mlp = mean_absolute_error(Ytest, y_pred_mlp)
print("Multilayer Perceptron Regression:")
print(f"Mean Squared Error (MSE): {mse_mlp:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_mlp:.2f}")
print(f"R2 Score: {r2_mlp:.2f}")
print(f"Mean Absolute Error (MAE): {mae_mlp:.2f}\n")

y_pred=rf_reg.predict(Xtest)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(range(len(Ytest)), Ytest, color='blue', label='True AQI')
plt.scatter(range(len(y_pred)), y_pred, color='red', label='Predicted AQI')
plt.title('True vs Predicted AQI')
plt.xlabel('Sample Index')
plt.ylabel('AQI')
plt.legend()
plt.show()

location_category_counts = df.groupby(['Location', 'AQI Category']).size().unstack()
print(location_category_counts)

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# Ensure there are no NaN values
location_category_counts = location_category_counts.fillna(0)

# Convert index to string (if needed)
location_category_counts.index = location_category_counts.index.astype(str)

# Define custom colors for AQI categories
aqi_colors = {
    "Good": "green",
    "Moderate": "yellow",
    "Unhealthy for Sensitive Groups": "orange",
    "Unhealthy": "red",
    "Very Unhealthy": "purple",
    "Hazardous": "maroon"
}

# Reorder colors based on the DataFrame column order
category_order = location_category_counts.columns.tolist()
color_list = [aqi_colors[category] for category in category_order if category in aqi_colors]

# Plot stacked bar chart with custom colors
location_category_counts.plot(kind='bar', stacked=True, figsize=(12, 6), color=color_list)

# Add labels and title
plt.title('Weather Situation by Location (AQI Categories)')
plt.xlabel('Location')
plt.ylabel('Count')
plt.legend(title='AQI Category')
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.tight_layout()  # Adjust layout to fit everything
plt.show()

import matplotlib.pyplot as plt

# Choose a location
location = 'Anderkilla'  # Replace with any location in your dataset

# Filter data for the selected location
location_data = df[df['Location'] == location]['AQI Category'].value_counts()

# Define custom colors for AQI categories
aqi_colors = {
    "Good": "green",
    "Moderate": "yellow",
    "Unhealthy for Sensitive Groups": "orange",
    "Unhealthy": "red",
    "Very Unhealthy": "purple",
    "Hazardous": "maroon"
}

# Ensure only present categories get colors
color_list = [aqi_colors[category] for category in location_data.index if category in aqi_colors]

# Plot pie chart with custom colors
location_data.plot(kind='pie', autopct='%1.1f%%', figsize=(8, 8), colors=color_list)

# Add title and formatting
plt.title(f'AQI Categories in {location}')
plt.ylabel('')  # Remove y-axis label for cleaner visualization
plt.show()

# Choose a location
location = 'Bayejid'  # Replace with any location in your dataset

# Filter data for the selected location
location_data = df[df['Location'] == location]['AQI Category'].value_counts()

# Define custom colors for AQI categories
aqi_colors = {
    "Good": "green",
    "Moderate": "yellow",
    "Unhealthy for Sensitive Groups": "orange",
    "Unhealthy": "red",
    "Very Unhealthy": "purple",
    "Hazardous": "maroon"
}

# Ensure only present categories get colors
color_list = [aqi_colors[category] for category in location_data.index if category in aqi_colors]

# Plot pie chart with custom colors
location_data.plot(kind='pie', autopct='%1.1f%%', figsize=(8, 8), colors=color_list)

# Add title and formatting
plt.title(f'AQI Categories in {location}')
plt.ylabel('')  # Remove y-axis label for cleaner visualization
plt.show()

# Choose a location
location = 'Dewanhat'  # Replace with any location in your dataset

# Filter data for the selected location
location_data = df[df['Location'] == location]['AQI Category'].value_counts()

# Define custom colors for AQI categories
aqi_colors = {
    "Good": "green",
    "Moderate": "yellow",
    "Unhealthy for Sensitive Groups": "orange",
    "Unhealthy": "red",
    "Very Unhealthy": "purple",
    "Hazardous": "maroon"
}

# Ensure only present categories get colors
color_list = [aqi_colors[category] for category in location_data.index if category in aqi_colors]

# Plot pie chart with custom colors
location_data.plot(kind='pie', autopct='%1.1f%%', figsize=(8, 8), colors=color_list)

# Add title and formatting
plt.title(f'AQI Categories in {location}')
plt.ylabel('')  # Remove y-axis label for cleaner visualization
plt.show()

import matplotlib.pyplot as plt

# Choose a location
location = 'Kotowali'  # Replace with any location in your dataset

# Filter data for the selected location
location_data = df[df['Location'] == location]['AQI Category'].value_counts()

# Define custom colors for AQI categories
aqi_colors = {
    "Good": "green",
    "Moderate": "yellow",
    "Unhealthy for Sensitive Groups": "orange",
    "Unhealthy": "red",
    "Very Unhealthy": "purple",
    "Hazardous": "maroon"
}

# Ensure only present categories get colors
color_list = [aqi_colors[category] for category in location_data.index if category in aqi_colors]

# Plot pie chart with custom colors
location_data.plot(kind='pie', autopct='%1.1f%%', figsize=(8, 8), colors=color_list)

# Add title and formatting
plt.title(f'AQI Categories in {location}')
plt.ylabel('')  # Remove y-axis label for cleaner visualization
plt.show()

import matplotlib.pyplot as plt

# Choose a location
location = 'New Market'  # Replace with any location in your dataset

# Filter data for the selected location
location_data = df[df['Location'] == location]['AQI Category'].value_counts()

# Define custom colors for AQI categories
aqi_colors = {
    "Good": "green",
    "Moderate": "yellow",
    "Unhealthy for Sensitive Groups": "orange",
    "Unhealthy": "red",
    "Very Unhealthy": "purple",
    "Hazardous": "maroon"
}

# Ensure only present categories get colors
color_list = [aqi_colors[category] for category in location_data.index if category in aqi_colors]

# Plot pie chart with custom colors
location_data.plot(kind='pie', autopct='%1.1f%%', figsize=(8, 8), colors=color_list)

# Add title and formatting
plt.title(f'AQI Categories in {location}')
plt.ylabel('')  # Remove y-axis label for cleaner visualization
plt.show()

"""Checking with user input:"""

import pandas as pd
import numpy as np
from sklearn.neural_network import MLPRegressor, MLPClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load the dataset
data = pd.read_csv('AQIFinalDataset.csv')

# Features and targets
X = data[['CO', 'SO2', 'NO2', 'O3', 'PM2.5', 'PM10']]
y_aqi = data['AQI']
y_category = data['AQI Category']

# Split the data
X_train, X_test, y_aqi_train, y_aqi_test, y_category_train, y_category_test = train_test_split(
    X, y_aqi, y_category, test_size=0.2, random_state=15
)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Decision Tree models
dt_reg = DecisionTreeRegressor(max_depth=5, random_state=15)
dt_reg.fit(X_train_scaled, y_aqi_train)
dt_clf = DecisionTreeClassifier(max_depth=5, random_state=15)
dt_clf.fit(X_train_scaled, y_category_train)

# Train Random Forest models
rf_reg = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=15)
rf_reg.fit(X_train_scaled, y_aqi_train)
rf_clf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=15)
rf_clf.fit(X_train_scaled, y_category_train)

# Train MLP models
mlp_reg = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=2000, random_state=15)
mlp_reg.fit(X_train_scaled, y_aqi_train)
mlp_clf = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=2000, random_state=15)
mlp_clf.fit(X_train_scaled, y_category_train)

# Function to predict AQI and AQI Category from user input
def predict_aqi_and_category():
    print("Enter pollutant values:")
    co = float(input("CO (ppm): "))
    so2 = float(input("SO2 (ppb): "))
    no2 = float(input("NO2 (ppb): "))
    o3 = float(input("O3 (ppb): "))
    pm25 = float(input("PM2.5 (µg/m³): "))
    pm10 = float(input("PM10 (µg/m³): "))

    # Create input as a DataFrame with feature names
    input_data = pd.DataFrame([[co, so2, no2, o3, pm25, pm10]],
                              columns=['CO', 'SO2', 'NO2', 'O3', 'PM2.5', 'PM10'])

    # Scale the input
    input_scaled = scaler.transform(input_data)

    # Predict AQI and AQI Category for each model
    dt_aqi_pred = dt_reg.predict(input_scaled)[0]
    dt_category_pred = dt_clf.predict(input_scaled)[0]
    rf_aqi_pred = rf_reg.predict(input_scaled)[0]
    rf_category_pred = rf_clf.predict(input_scaled)[0]
    mlp_aqi_pred = mlp_reg.predict(input_scaled)[0]
    mlp_category_pred = mlp_clf.predict(input_scaled)[0]

    # Print results
    print("\nPredictions:")
    print("Decision Tree:")
    print(f"  Predicted AQI: {dt_aqi_pred:.2f}")
    print(f"  Predicted AQI Category: {dt_category_pred}")
    print("Random Forest:")
    print(f"  Predicted AQI: {rf_aqi_pred:.2f}")
    print(f"  Predicted AQI Category: {rf_category_pred}")
    print("Multilayer Perceptron:")
    print(f"  Predicted AQI: {mlp_aqi_pred:.2f}")
    print(f"  Predicted AQI Category: {mlp_category_pred}\n")

# Run the prediction function
if __name__ == "__main__":
    while True:
        predict_aqi_and_category()
        cont = input("Do you want to predict again? (yes/no): ").lower()
        if cont != 'yes':
            break